/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Setup Status */
        get: operations["setup_status_api_v1_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Csrf */
        get: operations["csrf_api_v1_auth_csrf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/administrator": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Administrator */
        post: operations["create_administrator_api_v1_setup_administrator_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/two-factor": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Status */
        get: operations["status_api_v1_auth_two_factor_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/two-factor/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify */
        post: operations["verify_api_v1_auth_two_factor_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/two-factor/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cancel */
        post: operations["cancel_api_v1_auth_two_factor_cancel_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/two-factor/enroll": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll */
        post: operations["enroll_api_v1_auth_two_factor_enroll_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/two-factor/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm */
        post: operations["confirm_api_v1_auth_two_factor_confirm_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/two-factor/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Disable */
        post: operations["disable_api_v1_auth_two_factor_disable_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/two-factor/recovery-codes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate */
        post: operations["regenerate_api_v1_auth_two_factor_recovery_codes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Preferences */
        put: operations["save_preferences_api_v1_settings_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Onboarding */
        put: operations["save_onboarding_api_v1_settings_onboarding_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/postgresql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Postgresql */
        put: operations["save_postgresql_api_v1_settings_postgresql_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/mqtt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Mqtt */
        put: operations["save_mqtt_api_v1_settings_mqtt_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/smtp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Smtp */
        put: operations["save_smtp_api_v1_settings_smtp_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/postgresql/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Postgresql */
        post: operations["test_postgresql_api_v1_settings_postgresql_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/mqtt/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Mqtt */
        post: operations["test_mqtt_api_v1_settings_mqtt_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/smtp/test": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Test Smtp */
        post: operations["test_smtp_api_v1_settings_smtp_test_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/diagnostics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Diagnostics */
        get: operations["diagnostics_api_v1_diagnostics_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/history/capabilities": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** History Capabilities */
        get: operations["history_capabilities_api_v1_history_capabilities_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Vehicles */
        get: operations["vehicles_api_v1_vehicles_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vehicle_id}/history-window": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * History Window
         * @description Resolve a saved-timezone calendar selection for one existing vehicle.
         *
         *     The response is deliberately a small, stable hand-off: callers retain these
         *     UTC bounds for list pagination instead of resolving a new moving "now".
         */
        get: operations["history_window_api_v1_vehicles__vehicle_id__history_window_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vehicle_id}/trip-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Trip Summary
         * @description Aggregate a vehicle's complete explicit interval in one bounded SQL query.
         */
        get: operations["trip_summary_api_v1_vehicles__vehicle_id__trip_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/vehicles/{vehicle_id}/charge-summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Charge Summary
         * @description Aggregate one vehicle's complete UTC interval without loading charge rows.
         */
        get: operations["charge_summary_api_v1_vehicles__vehicle_id__charge_summary_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trips */
        get: operations["trips_api_v1_trips_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/charges": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Charges */
        get: operations["charges_api_v1_charges_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trip */
        get: operations["trip_api_v1_trips__trip_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/charges/{charge_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Charge */
        get: operations["charge_api_v1_charges__charge_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trip Series */
        get: operations["trip_series_api_v1_trips__trip_id__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/charges/{charge_id}/series": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Charge Series */
        get: operations["charge_series_api_v1_charges__charge_id__series_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/trips/{trip_id}/trajectory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Trajectory */
        get: operations["trajectory_api_v1_trips__trip_id__trajectory_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_api_v1_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthResponse */
        AuthResponse: {
            /** Csrf Token */
            csrf_token: string;
            /** Username */
            username: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "authenticated";
        };
        /** Capability */
        Capability: {
            /** Available */
            available: boolean;
            /** Reason */
            reason?: ("insufficient_permissions" | "incompatible_schema") | null;
        };
        /** ChallengeResponse */
        ChallengeResponse: {
            /** Csrf Token */
            csrf_token: string;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            status: "two_factor_required";
            /**
             * Expires In
             * @default 300
             */
            expires_in: number;
        };
        /** ChangePasswordInput */
        ChangePasswordInput: {
            proof?: components["schemas"]["FactorProof"] | null;
            /**
             * Current Password
             * Format: password
             */
            current_password: string;
            /**
             * New Password
             * Format: password
             */
            new_password: string;
            /**
             * Password Confirmation
             * Format: password
             */
            password_confirmation: string;
        };
        /** Charge */
        Charge: {
            /** Id */
            id: number;
            /** Vehicle Id */
            vehicle_id: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** End */
            end: string | null;
            /** Duration Min */
            duration_min: number | null;
            /** Energy Added Kwh */
            energy_added_kwh: number | null;
            /** Place */
            place: string | null;
            /** Start Battery Level */
            start_battery_level: number | null;
            /** End Battery Level */
            end_battery_level: number | null;
            /** Recorded Energy Used Kwh */
            recorded_energy_used_kwh: number | null;
            /** Cost */
            cost: number | null;
        };
        /** ChargePage */
        ChargePage: {
            /** Items */
            items: components["schemas"]["Charge"][];
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
        };
        /** ChargePeriodSummary */
        ChargePeriodSummary: {
            /** Vehicle Id */
            vehicle_id: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Total Count */
            total_count: number;
            /** Ended Count */
            ended_count: number;
            /** Not Ended Count */
            not_ended_count: number;
            /** Energy Added Kwh */
            energy_added_kwh: number | null;
            /** Duration Min */
            duration_min: number | null;
            /** Cost */
            cost: number | null;
            /** Currency */
            currency: ("AUD" | "CAD" | "CHF" | "CNY" | "DKK" | "EUR" | "GBP" | "JPY" | "NOK" | "NZD" | "PLN" | "SEK" | "USD") | null;
            energy_added_coverage: components["schemas"]["MetricCoverage"];
            duration_coverage: components["schemas"]["MetricCoverage"];
            cost_coverage: components["schemas"]["MetricCoverage"];
            cost_capability: components["schemas"]["Capability"];
        };
        /** ChargeSeries */
        ChargeSeries: {
            /** Charge Id */
            charge_id: number;
            capability: components["schemas"]["Capability"];
            /** Series */
            series: components["schemas"]["TimeSeries"][];
        };
        /** ConfirmInput */
        ConfirmInput: {
            /**
             * Current Password
             * Format: password
             */
            current_password: string;
            /**
             * Code
             * Format: password
             */
            code: string;
        };
        /** CreateAdminInput */
        CreateAdminInput: {
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Password Confirmation
             * Format: password
             */
            password_confirmation: string;
        };
        /** CsrfResponse */
        CsrfResponse: {
            /** Csrf Token */
            csrf_token: string;
        };
        /** Diagnostics */
        Diagnostics: {
            postgresql: components["schemas"]["PostgreSQLResponse"];
            mqtt: components["schemas"]["MQTTResponse"];
            smtp: components["schemas"]["SMTPResponse"];
        };
        /** EnrollmentResponse */
        EnrollmentResponse: {
            /** Secret */
            secret: string;
            /** Provisioning Uri */
            provisioning_uri: string;
            /**
             * Expires In
             * @default 600
             */
            expires_in: number;
        };
        /** FactorProof */
        FactorProof: {
            /**
             * Method
             * @enum {string}
             */
            method: "totp" | "recovery_code";
            /**
             * Code
             * Format: password
             */
            code: string;
        };
        /** FactorStatus */
        FactorStatus: {
            /** Enabled */
            enabled: boolean;
            /** Recovery Codes Remaining */
            recovery_codes_remaining: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** HistoryCapabilities */
        HistoryCapabilities: {
            /** Capabilities */
            capabilities: {
                [key: string]: components["schemas"]["Capability"];
            };
        };
        /** LoginInput */
        LoginInput: {
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /** MQTTInput */
        MQTTInput: {
            /**
             * Host
             * @default
             */
            host: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /**
             * Port
             * @default 1883
             */
            port: number;
            /**
             * Tls
             * @default false
             */
            tls: boolean;
            /**
             * Verify Tls
             * @default true
             */
            verify_tls: boolean;
            /**
             * Topic Prefix
             * @default teslamate
             */
            topic_prefix: string;
            password?: components["schemas"]["PasswordChange"];
        };
        /** MQTTResponse */
        MQTTResponse: {
            /**
             * Password Set
             * @default false
             */
            password_set: boolean;
            /**
             * Version
             * @default 0
             */
            version: number;
            /**
             * Test Available
             * @default true
             */
            test_available: boolean;
            /**
             * Status
             * @default disabled
             * @enum {string}
             */
            status: "unconfigured" | "unverified" | "disabled" | "skipped" | "success" | "failure";
            /**
             * Host
             * @default
             */
            host: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /**
             * Port
             * @default 1883
             */
            port: number;
            /**
             * Tls
             * @default false
             */
            tls: boolean;
            /**
             * Verify Tls
             * @default true
             */
            verify_tls: boolean;
            /**
             * Topic Prefix
             * @default teslamate
             */
            topic_prefix: string;
            test_result?: components["schemas"]["MQTTTestResult"] | null;
        };
        /** MQTTTestResult */
        MQTTTestResult: {
            /** Version */
            version: number;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "failure";
            /**
             * Code
             * @enum {string}
             */
            code: "subscription_accepted" | "message_received" | "delivery_accepted" | "disabled" | "skipped" | "unconfigured" | "invalid_credentials" | "unavailable" | "timeout" | "tls_error" | "configuration_changed" | "busy" | "subscription_rejected" | "sender_rejected" | "recipient_rejected" | "message_rejected" | "tls_unavailable" | "protocol_error";
            /**
             * Tested At
             * Format: date-time
             */
            tested_at: string;
            /**
             * Persisted
             * @default false
             */
            persisted: boolean;
            /**
             * Message Received
             * @default false
             */
            message_received: boolean;
        };
        /** ManagementInput */
        ManagementInput: {
            /**
             * Current Password
             * Format: password
             */
            current_password: string;
            proof: components["schemas"]["FactorProof"];
        };
        /**
         * MetricCoverage
         * @description Validity of one period aggregate; applicability is every ended drive.
         */
        MetricCoverage: {
            /** Applicable Count */
            applicable_count: number;
            /** Valid Count */
            valid_count: number;
            /** Reason */
            reason: ("no_ended_records" | "no_valid_values" | "zero_denominator" | "unavailable") | null;
        };
        /** Onboarding */
        Onboarding: {
            /**
             * Step
             * @default preferences
             * @enum {string}
             */
            step: "preferences" | "postgresql" | "mqtt" | "smtp" | "two_factor" | "review";
            /**
             * Completed
             * @default false
             */
            completed: boolean;
        };
        /** PasswordChange */
        PasswordChange: {
            /**
             * Action
             * @default retain
             * @enum {string}
             */
            action: "retain" | "replace" | "clear";
            /** Value */
            value?: string | null;
        };
        /** PasswordInput */
        PasswordInput: {
            /**
             * Current Password
             * Format: password
             */
            current_password: string;
        };
        /** Point */
        Point: {
            /** Id */
            id: number;
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Latitude */
            latitude: number;
            /** Longitude */
            longitude: number;
            /** Segment Id */
            segment_id: number;
        };
        /** PostgreSQLInput */
        PostgreSQLInput: {
            /**
             * Host
             * @default
             */
            host: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /**
             * Port
             * @default 5432
             */
            port: number;
            /**
             * Database
             * @default teslamate
             */
            database: string;
            /**
             * Sslmode
             * @default prefer
             * @enum {string}
             */
            sslmode: "disable" | "allow" | "prefer" | "require" | "verify-ca" | "verify-full";
            password?: components["schemas"]["PasswordChange"];
        };
        /** PostgreSQLResponse */
        PostgreSQLResponse: {
            /**
             * Password Set
             * @default false
             */
            password_set: boolean;
            /**
             * Version
             * @default 0
             */
            version: number;
            /**
             * Test Available
             * @default true
             */
            test_available: boolean;
            /**
             * Host
             * @default
             */
            host: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /**
             * Port
             * @default 5432
             */
            port: number;
            /**
             * Database
             * @default teslamate
             */
            database: string;
            /**
             * Sslmode
             * @default prefer
             * @enum {string}
             */
            sslmode: "disable" | "allow" | "prefer" | "require" | "verify-ca" | "verify-full";
            /**
             * Status
             * @default disabled
             * @enum {string}
             */
            status: "unconfigured" | "unverified" | "disabled" | "skipped" | "success" | "failure";
            test_result?: components["schemas"]["PostgreSQLTestResult"] | null;
        };
        /** PostgreSQLTestResult */
        PostgreSQLTestResult: {
            /** Version */
            version: number;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "failure";
            /**
             * Code
             * @enum {string}
             */
            code: "ok" | "empty_data" | "unconfigured" | "disabled" | "skipped" | "invalid_credentials" | "unavailable" | "timeout" | "incompatible_schema" | "unsafe_permissions" | "insufficient_permissions" | "configuration_changed";
            /**
             * Tested At
             * Format: date-time
             */
            tested_at: string;
            /**
             * Persisted
             * @default false
             */
            persisted: boolean;
        };
        /** Preferences */
        Preferences: {
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "zh";
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /**
             * Tile Url
             * @default https://tile.openstreetmap.org/{z}/{x}/{y}.png
             */
            tile_url: string;
            /**
             * Range Basis
             * @enum {string}
             */
            range_basis?: "rated" | "ideal";
            /** Display Currency */
            display_currency?: ("AUD" | "CAD" | "CHF" | "CNY" | "DKK" | "EUR" | "GBP" | "JPY" | "NOK" | "NZD" | "PLN" | "SEK" | "USD") | null;
        };
        /** PreferencesResponse */
        PreferencesResponse: {
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "zh";
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /**
             * Tile Url
             * @default https://tile.openstreetmap.org/{z}/{x}/{y}.png
             */
            tile_url: string;
            /**
             * Range Basis
             * @default rated
             * @enum {string}
             */
            range_basis: "rated" | "ideal";
            /** Display Currency */
            display_currency?: ("AUD" | "CAD" | "CHF" | "CNY" | "DKK" | "EUR" | "GBP" | "JPY" | "NOK" | "NZD" | "PLN" | "SEK" | "USD") | null;
            /**
             * Saved
             * @default false
             */
            saved: boolean;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
        };
        /** RecoveryCodesResponse */
        RecoveryCodesResponse: {
            /** Csrf Token */
            csrf_token: string;
            /** Username */
            username: string;
            /**
             * Status
             * @default authenticated
             * @constant
             */
            status: "authenticated";
            /** Recovery Codes */
            recovery_codes: string[];
        };
        /**
         * ResolvedHistoryWindow
         * @description A local-calendar selection resolved once for reuse by later requests.
         */
        ResolvedHistoryWindow: {
            /**
             * Preset
             * @enum {string}
             */
            preset: "today" | "last_7_days" | "last_30_days" | "this_month" | "this_year" | "all_history" | "custom";
            /** Timezone */
            timezone: string;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Is Empty */
            is_empty: boolean;
        };
        /** SMTPInput */
        SMTPInput: {
            /**
             * Host
             * @default
             */
            host: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /**
             * Port
             * @default 587
             */
            port: number;
            /**
             * Tls Mode
             * @default starttls
             * @enum {string}
             */
            tls_mode: "implicit" | "starttls" | "plain";
            /**
             * Verify Tls
             * @default true
             */
            verify_tls: boolean;
            /**
             * Sender
             * @default
             */
            sender: string;
            password?: components["schemas"]["PasswordChange"];
        };
        /** SMTPResponse */
        SMTPResponse: {
            /**
             * Password Set
             * @default false
             */
            password_set: boolean;
            /**
             * Version
             * @default 0
             */
            version: number;
            /**
             * Test Available
             * @default true
             */
            test_available: boolean;
            /**
             * Status
             * @default disabled
             * @enum {string}
             */
            status: "unconfigured" | "unverified" | "disabled" | "skipped" | "success" | "failure";
            /**
             * Host
             * @default
             */
            host: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /**
             * Port
             * @default 587
             */
            port: number;
            /**
             * Tls Mode
             * @default starttls
             * @enum {string}
             */
            tls_mode: "implicit" | "starttls" | "plain";
            /**
             * Verify Tls
             * @default true
             */
            verify_tls: boolean;
            /**
             * Sender
             * @default
             */
            sender: string;
            test_result?: components["schemas"]["SMTPTestResult"] | null;
        };
        /** SMTPTestInput */
        SMTPTestInput: {
            /** Recipient */
            recipient: string;
        };
        /** SMTPTestResult */
        SMTPTestResult: {
            /** Version */
            version: number;
            /**
             * Status
             * @enum {string}
             */
            status: "success" | "failure";
            /**
             * Code
             * @enum {string}
             */
            code: "subscription_accepted" | "message_received" | "delivery_accepted" | "disabled" | "skipped" | "unconfigured" | "invalid_credentials" | "unavailable" | "timeout" | "tls_error" | "configuration_changed" | "busy" | "subscription_rejected" | "sender_rejected" | "recipient_rejected" | "message_rejected" | "tls_unavailable" | "protocol_error";
            /**
             * Tested At
             * Format: date-time
             */
            tested_at: string;
            /**
             * Persisted
             * @default false
             */
            persisted: boolean;
            /**
             * Delivery Accepted
             * @default false
             */
            delivery_accepted: boolean;
        };
        /** @enum {string} */
        SeriesAggregation: "raw" | "mean_min_max" | "last";
        /** @enum {string} */
        SeriesName: "speed" | "power" | "battery" | "inside_temperature" | "outside_temperature" | "elevation";
        /**
         * SeriesPoint
         * @description One raw sample or one equal-width aggregate bucket.
         */
        SeriesPoint: {
            /**
             * Time
             * Format: date-time
             */
            time: string;
            /** Mean */
            mean?: number | null;
            /** Min */
            min?: number | null;
            /** Max */
            max?: number | null;
            /** Value */
            value?: number | null;
            /** Discontinuity */
            discontinuity: boolean;
        };
        /** SettingsResponse */
        SettingsResponse: {
            preferences?: components["schemas"]["PreferencesResponse"];
            postgresql?: components["schemas"]["PostgreSQLResponse"];
            mqtt?: components["schemas"]["MQTTResponse"];
            smtp?: components["schemas"]["SMTPResponse"];
            onboarding?: components["schemas"]["Onboarding"];
        };
        /** SetupStatus */
        SetupStatus: {
            /** Csrf Token */
            csrf_token: string;
            /** Administrator Exists */
            administrator_exists: boolean;
        };
        /** TimeSeries */
        TimeSeries: {
            name: components["schemas"]["SeriesName"];
            /** Unit */
            unit: string;
            /** Start */
            start: string | null;
            /** End */
            end: string | null;
            /** Sample Count */
            sample_count: number;
            /** Bucket Count */
            bucket_count: number;
            aggregation: components["schemas"]["SeriesAggregation"];
            capability: components["schemas"]["Capability"];
            /** Points */
            points: components["schemas"]["SeriesPoint"][];
        };
        /** Trajectory */
        Trajectory: {
            /** Trip Id */
            trip_id: number;
            /** Points */
            points: components["schemas"]["Point"][];
            /** Simplified */
            simplified: boolean;
            /** Total Points */
            total_points: number;
        };
        /** Trip */
        Trip: {
            /** Id */
            id: number;
            /** Vehicle Id */
            vehicle_id: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /** End */
            end: string | null;
            /** Duration Min */
            duration_min: number | null;
            /** Distance Km */
            distance_km: number | null;
            /** Speed Max Kmh */
            speed_max_kmh: number | null;
            /** Start Place */
            start_place: string | null;
            /** End Place */
            end_place: string | null;
            /** Start Battery Level */
            start_battery_level: number | null;
            /** End Battery Level */
            end_battery_level: number | null;
            /** Estimated Energy Kwh */
            estimated_energy_kwh: number | null;
            /** Estimated Average Consumption Wh Per Km */
            estimated_average_consumption_wh_per_km: number | null;
        };
        /** TripPage */
        TripPage: {
            /** Items */
            items: components["schemas"]["Trip"][];
            /** Next Cursor */
            next_cursor: string | null;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
        };
        /** TripPeriodSummary */
        TripPeriodSummary: {
            /** Vehicle Id */
            vehicle_id: number;
            /**
             * Start
             * Format: date-time
             */
            start: string;
            /**
             * End
             * Format: date-time
             */
            end: string;
            /** Total Count */
            total_count: number;
            /** Ended Count */
            ended_count: number;
            /** Not Ended Count */
            not_ended_count: number;
            /** Distance Km */
            distance_km: number | null;
            /** Duration Min */
            duration_min: number | null;
            /** Estimated Energy Kwh */
            estimated_energy_kwh: number | null;
            /** Estimated Average Consumption Wh Per Km */
            estimated_average_consumption_wh_per_km: number | null;
            distance_coverage: components["schemas"]["MetricCoverage"];
            duration_coverage: components["schemas"]["MetricCoverage"];
            estimated_energy_coverage: components["schemas"]["MetricCoverage"];
            estimated_average_consumption_coverage: components["schemas"]["MetricCoverage"];
            estimate_capability: components["schemas"]["Capability"];
        };
        /** TripSeries */
        TripSeries: {
            /** Trip Id */
            trip_id: number;
            capability: components["schemas"]["Capability"];
            /** Series */
            series: components["schemas"]["TimeSeries"][];
        };
        /** UserResponse */
        UserResponse: {
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
        /** Vehicle */
        Vehicle: {
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Model */
            model: string | null;
        };
        /** Vehicles */
        Vehicles: {
            /** Items */
            items: components["schemas"]["Vehicle"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    setup_status_api_v1_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    csrf_api_v1_auth_csrf_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    create_administrator_api_v1_setup_administrator_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdminInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"] | components["schemas"]["ChallengeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_password_api_v1_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    status_api_v1_auth_two_factor_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FactorStatus"];
                };
            };
        };
    };
    verify_api_v1_auth_two_factor_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FactorProof"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_api_v1_auth_two_factor_cancel_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    enroll_api_v1_auth_two_factor_enroll_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasswordInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    confirm_api_v1_auth_two_factor_confirm_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfirmInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    disable_api_v1_auth_two_factor_disable_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManagementInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    regenerate_api_v1_auth_two_factor_recovery_codes_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ManagementInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryCodesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    save_preferences_api_v1_settings_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Preferences"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_onboarding_api_v1_settings_onboarding_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Onboarding"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_postgresql_api_v1_settings_postgresql_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostgreSQLInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_mqtt_api_v1_settings_mqtt_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MQTTInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_smtp_api_v1_settings_smtp_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SMTPInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    test_postgresql_api_v1_settings_postgresql_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PostgreSQLTestResult"];
                };
            };
        };
    };
    test_mqtt_api_v1_settings_mqtt_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MQTTTestResult"];
                };
            };
        };
    };
    test_smtp_api_v1_settings_smtp_test_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SMTPTestInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SMTPTestResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    diagnostics_api_v1_diagnostics_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Diagnostics"];
                };
            };
        };
    };
    history_capabilities_api_v1_history_capabilities_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryCapabilities"];
                };
            };
        };
    };
    vehicles_api_v1_vehicles_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Vehicles"];
                };
            };
        };
    };
    history_window_api_v1_vehicles__vehicle_id__history_window_get: {
        parameters: {
            query?: {
                preset?: "today" | "last_7_days" | "last_30_days" | "this_month" | "this_year" | "all_history" | "custom";
                start_date?: string | null;
                end_date?: string | null;
            };
            header?: never;
            path: {
                vehicle_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ResolvedHistoryWindow"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trip_summary_api_v1_vehicles__vehicle_id__trip_summary_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path: {
                vehicle_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripPeriodSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    charge_summary_api_v1_vehicles__vehicle_id__charge_summary_get: {
        parameters: {
            query: {
                start: string;
                end: string;
            };
            header?: never;
            path: {
                vehicle_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChargePeriodSummary"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trips_api_v1_trips_get: {
        parameters: {
            query?: {
                vehicle_id?: number | null;
                start?: string | null;
                end?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    charges_api_v1_charges_get: {
        parameters: {
            query?: {
                vehicle_id?: number | null;
                start?: string | null;
                end?: string | null;
                limit?: number;
                cursor?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChargePage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trip_api_v1_trips__trip_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trip"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    charge_api_v1_charges__charge_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                charge_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Charge"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trip_series_api_v1_trips__trip_id__series_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TripSeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    charge_series_api_v1_charges__charge_id__series_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                charge_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ChargeSeries"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    trajectory_api_v1_trips__trip_id__trajectory_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                trip_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Trajectory"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_api_v1_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
