/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/setup/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Setup Status */
        get: operations["setup_status_api_v1_setup_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/csrf": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Csrf */
        get: operations["csrf_api_v1_auth_csrf_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/setup/administrator": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create Administrator */
        post: operations["create_administrator_api_v1_setup_administrator_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Login */
        post: operations["login_api_v1_auth_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_auth_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/password": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Change Password */
        post: operations["change_password_api_v1_auth_password_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Settings */
        get: operations["get_settings_api_v1_settings_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Preferences */
        put: operations["save_preferences_api_v1_settings_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/onboarding": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Onboarding */
        put: operations["save_onboarding_api_v1_settings_onboarding_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/postgresql": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Postgresql */
        put: operations["save_postgresql_api_v1_settings_postgresql_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/mqtt": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Mqtt */
        put: operations["save_mqtt_api_v1_settings_mqtt_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/settings/smtp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Save Smtp */
        put: operations["save_smtp_api_v1_settings_smtp_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/readiness": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Readiness */
        get: operations["readiness_api_v1_readiness_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AuthResponse */
        AuthResponse: {
            /** Csrf Token */
            csrf_token: string;
            /** Username */
            username: string;
        };
        /** ChangePasswordInput */
        ChangePasswordInput: {
            /**
             * Current Password
             * Format: password
             */
            current_password: string;
            /**
             * New Password
             * Format: password
             */
            new_password: string;
            /**
             * Password Confirmation
             * Format: password
             */
            password_confirmation: string;
        };
        /** CreateAdminInput */
        CreateAdminInput: {
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
            /**
             * Password Confirmation
             * Format: password
             */
            password_confirmation: string;
        };
        /** CsrfResponse */
        CsrfResponse: {
            /** Csrf Token */
            csrf_token: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
            /** Version */
            version: string;
        };
        /** LoginInput */
        LoginInput: {
            /** Username */
            username: string;
            /**
             * Password
             * Format: password
             */
            password: string;
        };
        /** MQTTInput */
        MQTTInput: {
            /**
             * Host
             * @default
             */
            host: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /**
             * Port
             * @default 1883
             */
            port: number;
            /**
             * Tls
             * @default false
             */
            tls: boolean;
            /**
             * Verify Tls
             * @default true
             */
            verify_tls: boolean;
            /**
             * Topic Prefix
             * @default teslamate
             */
            topic_prefix: string;
            password?: components["schemas"]["PasswordChange"];
        };
        /** MQTTResponse */
        MQTTResponse: {
            /**
             * Password Set
             * @default false
             */
            password_set: boolean;
            /**
             * Version
             * @default 0
             */
            version: number;
            /**
             * Status
             * @default disabled
             * @enum {string}
             */
            status: "unconfigured" | "unverified" | "disabled" | "skipped";
            /**
             * Test Available
             * @default false
             * @constant
             */
            test_available: false;
            /**
             * Host
             * @default
             */
            host: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /**
             * Port
             * @default 1883
             */
            port: number;
            /**
             * Tls
             * @default false
             */
            tls: boolean;
            /**
             * Verify Tls
             * @default true
             */
            verify_tls: boolean;
            /**
             * Topic Prefix
             * @default teslamate
             */
            topic_prefix: string;
        };
        /** Onboarding */
        Onboarding: {
            /**
             * Step
             * @default preferences
             * @enum {string}
             */
            step: "preferences" | "postgresql" | "mqtt" | "smtp" | "review";
            /**
             * Completed
             * @default false
             */
            completed: boolean;
        };
        /** PasswordChange */
        PasswordChange: {
            /**
             * Action
             * @default retain
             * @enum {string}
             */
            action: "retain" | "replace" | "clear";
            /** Value */
            value?: string | null;
        };
        /** PostgreSQLInput */
        PostgreSQLInput: {
            /**
             * Host
             * @default
             */
            host: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /**
             * Port
             * @default 5432
             */
            port: number;
            /**
             * Database
             * @default teslamate
             */
            database: string;
            /**
             * Sslmode
             * @default prefer
             * @enum {string}
             */
            sslmode: "disable" | "allow" | "prefer" | "require" | "verify-ca" | "verify-full";
            password?: components["schemas"]["PasswordChange"];
        };
        /** PostgreSQLResponse */
        PostgreSQLResponse: {
            /**
             * Password Set
             * @default false
             */
            password_set: boolean;
            /**
             * Version
             * @default 0
             */
            version: number;
            /**
             * Status
             * @default disabled
             * @enum {string}
             */
            status: "unconfigured" | "unverified" | "disabled" | "skipped";
            /**
             * Test Available
             * @default false
             * @constant
             */
            test_available: false;
            /**
             * Host
             * @default
             */
            host: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /**
             * Port
             * @default 5432
             */
            port: number;
            /**
             * Database
             * @default teslamate
             */
            database: string;
            /**
             * Sslmode
             * @default prefer
             * @enum {string}
             */
            sslmode: "disable" | "allow" | "prefer" | "require" | "verify-ca" | "verify-full";
        };
        /** Preferences */
        Preferences: {
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "zh";
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /**
             * Tile Url
             * @default https://tile.openstreetmap.org/{z}/{x}/{y}.png
             */
            tile_url: string;
        };
        /** PreferencesResponse */
        PreferencesResponse: {
            /**
             * Language
             * @default en
             * @enum {string}
             */
            language: "en" | "zh";
            /**
             * Timezone
             * @default UTC
             */
            timezone: string;
            /**
             * Tile Url
             * @default https://tile.openstreetmap.org/{z}/{x}/{y}.png
             */
            tile_url: string;
            /**
             * Saved
             * @default false
             */
            saved: boolean;
        };
        /** ReadinessResponse */
        ReadinessResponse: {
            /** Status */
            status: string;
            /** Service */
            service: string;
        };
        /** SMTPInput */
        SMTPInput: {
            /**
             * Host
             * @default
             */
            host: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /**
             * Port
             * @default 587
             */
            port: number;
            /**
             * Tls Mode
             * @default starttls
             * @enum {string}
             */
            tls_mode: "implicit" | "starttls" | "plain";
            /**
             * Verify Tls
             * @default true
             */
            verify_tls: boolean;
            /**
             * Sender
             * @default
             */
            sender: string;
            password?: components["schemas"]["PasswordChange"];
        };
        /** SMTPResponse */
        SMTPResponse: {
            /**
             * Password Set
             * @default false
             */
            password_set: boolean;
            /**
             * Version
             * @default 0
             */
            version: number;
            /**
             * Status
             * @default disabled
             * @enum {string}
             */
            status: "unconfigured" | "unverified" | "disabled" | "skipped";
            /**
             * Test Available
             * @default false
             * @constant
             */
            test_available: false;
            /**
             * Host
             * @default
             */
            host: string;
            /**
             * Username
             * @default
             */
            username: string;
            /**
             * Enabled
             * @default false
             */
            enabled: boolean;
            /**
             * Skipped
             * @default false
             */
            skipped: boolean;
            /**
             * Port
             * @default 587
             */
            port: number;
            /**
             * Tls Mode
             * @default starttls
             * @enum {string}
             */
            tls_mode: "implicit" | "starttls" | "plain";
            /**
             * Verify Tls
             * @default true
             */
            verify_tls: boolean;
            /**
             * Sender
             * @default
             */
            sender: string;
        };
        /** SettingsResponse */
        SettingsResponse: {
            preferences?: components["schemas"]["PreferencesResponse"];
            postgresql?: components["schemas"]["PostgreSQLResponse"];
            mqtt?: components["schemas"]["MQTTResponse"];
            smtp?: components["schemas"]["SMTPResponse"];
            onboarding?: components["schemas"]["Onboarding"];
        };
        /** SetupStatus */
        SetupStatus: {
            /** Csrf Token */
            csrf_token: string;
            /** Administrator Exists */
            administrator_exists: boolean;
        };
        /** UserResponse */
        UserResponse: {
            /** Username */
            username: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    setup_status_api_v1_setup_status_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SetupStatus"];
                };
            };
        };
    };
    csrf_api_v1_auth_csrf_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CsrfResponse"];
                };
            };
        };
    };
    create_administrator_api_v1_setup_administrator_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAdminInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    login_api_v1_auth_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_auth_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserResponse"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    change_password_api_v1_auth_password_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChangePasswordInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_settings_api_v1_settings_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
        };
    };
    save_preferences_api_v1_settings_preferences_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Preferences"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_onboarding_api_v1_settings_onboarding_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["Onboarding"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_postgresql_api_v1_settings_postgresql_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PostgreSQLInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_mqtt_api_v1_settings_mqtt_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["MQTTInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    save_smtp_api_v1_settings_smtp_put: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SMTPInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    readiness_api_v1_readiness_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReadinessResponse"];
                };
            };
        };
    };
}
